enum FILE_UPLOAD_TYPES {
  PAN_CARD = 'PAN',
  AADHAR_CARD = 'AADHAR',
  CANCELLED_CHEQUE = 'CCHEQUE',
  BANK_PASS_BOOK = 'BPASS',
  EDUCATION = 'EDU',
  SKILL_CERTIFICATION = 'SKILL',
  PROFILE_PHOTO = 'PPHOTO',
  USER_RESUME = 'RESUME',
}

export { FILE_UPLOAD_TYPES };